### ISSUE TITLE
Question: Derivative of sigmoid function ?

### ISSUE THREAD

**Issue by var23rav** [llSourcell/Make_a_neural_network#1]
Please verify this !

The derivative of the sigmoid function `S(x) = 1/ (1+e^−x )`
will be 
`e^x / ( (1+ e^x) ^ 2 )`    or    `S(x) * (1−S(x))`

Check https://en.wikipedia.org/wiki/Sigmoid_function

But [in the source code ](https://github.com/llSourcell/Make_a_neural_network/blob/master/demo.py#L24)
Derivative is mentioned in wrong way `x * (1 - x)`.

**Comment by fokussin** [comment]
The ```x``` in ```x * (1 - x)``` is the sigmoid function output.
```S(x)``` on Wikipedia is the sigmoid function and it returns a value based on input ```x```.
In this case, our function is ```sigmoid(x)``` and our derivative function is ```sigmoid_derivative(x)``` so we could write the formula like this ```sigmoid(x) * (1 - sigmoid(x))```.

**Comment by kwichmann** [comment]
I was wondering the same thing.

**Comment by var23rav** [comment]
Hi, @llSourcell the source code is correct but with name **sigmoid_derivate** it made some confusion.
Thanks to @kwichmann, the code look more readable now.
actually **output** variable is result of **sigmoid(x)** itself.
Check the **think()** [function that give the output](https://github.com/llSourcell/Make_a_neural_network/blob/master/demo.py#L49)

**Comment by var23rav** [comment]
Hi @llSourcell,
It would be better to rename the **__sigmoid_derivate()**  input parameter(x) to something like, **sigmoid_function_output**.
Little bit of explanation would have same my hours,
`S(x) = 1/ (1+e^−x )`
 **S'(x)** = _e^x / ( (1+ e^x) ^ 2 ) )_ **or** `S(x) * (1−S(x))`
